### ISSUE TITLE
Nested mu.yml files

### ISSUE THREAD

**Issue by cplee** [stelligent/mu#162]
Allow pipelines to be created from mu.yml files in nested folders of the repo.  

For example, a repo could have the following directory structure:

* dir1
   * mu.yml
* dir2
   * mu.yml

You should be able to run `mu -c dir1/mu.yml pipeline up` and `mu -c dir2/mu.yml pipeline up` to create to different pipelines.

This should be testable by run mu against the examples in the mu repo.

**Comment by timbaileyjones** [comment]
Clarification time:
1.  The title "Nested mu.yml files" suggests to me that one mu.yml refers to another, and the `-c` target should be included in the root `mu.yml`, similar to a line containing the C macro `#include` would be replaced by the body of a wholly different file.  But your first comment doesn't read like that at all.
2.  That means that there is still only one mu.yml in the context of a particular run of mu, but that it would reside a different directory (such as `./example/databases/mu.yml`).  In this case, the change is just to have it read the argument to `-c` instead of `mu.yml`... 

So assuming you mean #2, then my next question is: should 'mu' then `chdir()` to the directory containing the specified `mu.yml` file, so that references to the supplied `./examples/databases/mu.yml` be relative to the `./examples/databases` directory?

**Comment by cplee** [comment]
@timbaileyjones I've updated the title to help clarify.  Yes, only one mu.yml, just read from a subdirectory.

At this point, I'm guessing it may already work, so before you make any changes, i'd advise you to try it first.  If it works, then this issue can be closed.  If not, we can discuss approaches to fix.

**Comment by timbaileyjones** [comment]
You're right, @cplee.  The `-c filename` does seems to work already.  However, there is no `chdir()` to the basename of the `-c` argument.  I would think that would be essential, so that relative paths would work from the named `mu.yml` file's point of view.  
![image](https://user-images.githubusercontent.com/790126/32189183-5f2e2576-bd80-11e7-8860-c130f07bdf92.png)

Should I add such a chdir() to the named `mu.yml` file's directory?

**Comment by cplee** [comment]
@timbaileyjones thanks for validating.  So if the pipeline is able to successfully run with mu.yml in subdirectory, then i think we are done.  Don't think the chdir is necessary since we always resolve paths relative to the directory of the mu.yml

see: https://github.com/stelligent/mu/blob/develop/common/context.go#L41

**Comment by cplee** [comment]
Closing based on @timbaileyjones's findings
