### ISSUE TITLE
Add stack policies for critical resources to avoid replacement

### ISSUE THREAD

**Issue by cplee** [stelligent/mu#273]
Ensure stack policies exist to disallow replacement/deletion for:
* RDS
* KMS

**Comment by mneil** [comment]
I'm picking this up and started thinking about _how_ to handle it. My thoughts - please let me know if have any other ideas or insights:

 - Add a new default policy to the database stack
 - Add a new default policy to the IAM stacks that involve KMS
 - The policy will be to allow all actions but deny update or delete on KMS/Database resources
 - This policy will only be added when creating a stack (so it does not affect existing stacks / users)
 - Add a new flag to allow update / delete for that 1 request
    - Create a temporary policy that allows all actions so the resources can be modified then revert back

I think that gets us 90% of the way there to protecting resources - the flag must be set in order to modify. That will at least make users think about it.

**Comment by jeffb4** [comment]
You want to disallow actions "Update:Replace" and "Update:Delete" on the KMS CMK and RDS instance resources.

When you're implementing the flag, you shouldn't need to set a new policy and revert, you can instead specify a temporary policy just for that request, see "StackPolicyDuringUpdateBody" at https://docs.aws.amazon.com/sdk-for-go/api/service/cloudformation/#UpdateStackInput

**Comment by mneil** [comment]
Any suggestions for the flag name that will allow replace or delete actions on RDS and KMS resources?

I feel like `force` is good since it's common in unix but I also thought something more daunting like `unsafe` would be good too. Right now I'm leaning towards `unsafe`.

**Comment by cplee** [comment]
I agree that it should be daunting, and also i'll add that it doesn't need to be terse.  How about something like `--approve-data-loss`

**Comment by mneil** [comment]
Works for me. Says what it does. I'll go with that!

**Comment by cplee** [comment]
resolved in #341
