### ISSUE TITLE
period(.) in image tag in mu version 1.4.5

### ISSUE THREAD

**Issue by tushariscoolster** [stelligent/mu#308]
[32mUpsert repo for service 'api'[0m
No changes for stack 'kqed-repo-api'[0m
[32mBuilding service:'api' as image:969064053837.dkr.ecr.us-east-1.amazonaws.com/kqed-api:.cojYFx'[0m
[31mfunc1 ▶ ERROR [0m Error response from daemon: Error parsing reference: "969064053837.dkr.ecr.us-east-1.amazonaws.com/kqed-api:.cojYFx" is not a valid repository/tag
[31mfunc1 ▶ ERROR [0m

**Comment by akuma12** [comment]
Hi @tushariscoolster ,

Can you verify that the version of Mu that the Pipeline is using is 1.4.5? This issue should have been fixed in 1.4.4. If you go to Details for the "Image" stage of the Pipeline and look at the logs (you might have to click the "View in CloudWatch Logs" link) and see if you can find where it actually installs Mu in the container and verify that it's downloading the 1.4.5 release, that would help.

Thanks!
Jim

**Comment by tushariscoolster** [comment]
I will close this issues, as this .(period issue is fixed)
