### ISSUE TITLE
Add a Gemfile to Declare Ruby Dependency

### ISSUE THREAD

**Issue by BennyHarv3** [stelligent/mu#362]
[The Makefile](https://github.com/stelligent/mu/blob/master/Makefile) requires the `gem` tool, but our documentation does not explicitly state this.

A `Gemfile` should be added with all of the expected gems (looks like just `cfn-nag` at this point), and then the Makefile could be updated to install the gems locally instead of using `sudo` using [`bundler`](https://bundler.io/).

We could also remove the condition around `cfn-nag` and instead error out if Ruby, `gem`, or `bundler` isn't installed.

**Comment by cplee** [comment]
This requires another tool though, `bundler` and it seems a bit odd to add the Gemfile for a single tool.

**Comment by BennyHarv3** [comment]
We could just add Ruby as a documented dependency. It feels weird to run `sudo` in the middle of `make`, though, so maybe we could also just install the gem locally and refer to it?

**Comment by jeffb4** [comment]
My Very Ruby Thoughts:
A bare `sudo gem install` is hurtful for people who use rvm. 

`bundler install` is much more robust (it'll pivot to sudo if needed in the user's environment). It's also present on almost all Ruby installs.

If we want to keep the gem install because we never think the use of Ruby is going to go beyond cfn-nag, `gem install || sudo gem install` would be a kinder UX

**Comment by cplee** [comment]
I'm good with `gem install || sudo gem install` or even removing the gem install altogether and replace with a prerequisite and an update to the circleci config to install the dependency outside of the Makefile.
