### ISSUE TITLE
is mu no longer maintained?

### ISSUE THREAD

**Issue by dfuentes77** [stelligent/mu#438]
I'm noticing there have been no new releases since Nov/Dec 2018 and no new commits to `develop` branch in almost 3 months.  Is the team moving on to other things?  Just curious, I was considering trying it out since it looks very interesting.  But concerned if it's going stale and not going to be maintained. 

Thanks!

**Comment by wrkngu0** [comment]
Since I tried this project five+ months ago, I realized that all Mu ecosystem is not mature and acceptable only for development environments for now.
I faced with a couple of critical bugs and as consequences downtimes after all.
So I wrote own realization for ECS but confined only to service management. CI/CD handled by CodePipeline and CodeDeploy separately.

**Comment by AbhimanyuG** [comment]
Are there any active alternatives of mu?

**Comment by brentley** [comment]
Ecs CLI v2 is shaping up to be a good alternative, IMO.

**Comment by testep02** [comment]
I used to work for Stelligent, the company that wrote this tool. Since I left they have been acquired several times. It would not surprise me if the new owners of that company have put a halt to all work on this tool. That company makes their money from doing contract work for other companies. Time spent working on a tool like this is time not being spent on a contract. I would look for another alternative.

**Comment by karlskidmore** [comment]
@AbhimanyuG I just came across this today: https://stelligent.github.io/mutato/#/mutato-vs-mu

Not attempted to use it yet though.

**Comment by mneil** [comment]
Thanks everyone for your interest in Mu. We've had a good run with it but have ultimately decided, internally, not to continue to work on Mu. I will be updating the README to reflect this. I'll leave the repository open for a bit for continued discussion here but will, eventually, archive the repository.

@testep02 is right, we do make our money off of consulting. However, Open Source and consulting are not mutually exclusive. Mu afforded Stelligent a lot of opportunity as well as help our internal sales process. We have to walk a line of what code is proprietary and what is general purpose / non-differentiating work that we can share with the community.

@karlskidmore @AbhimanyuG we have been working on an alternative, https://github.com/stelligent/mutato/, and to be completely upfront we're still determining how best to support it going forward. Mutato's success will largely depend on our ability to use it internally. We build these tools for our own purposes / use. And internally they provide a lot of value. When we can, we share this work, so that everyone can use it.

We recently did a [podcast on Mutato, Mu, and OSS at Stelligent](https://stelligent.com/2020/05/12/devops-on-aws-radio-mutato-and-open-source-at-stelligent-episode-27/) that may be of interest.

As for non-Stelligent OSS similar to Mu:

 - [ECS CLI v2](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI.html)
 - [CDK - particulary APP Delivery](https://docs.aws.amazon.com/cdk/api/latest/docs/app-delivery-readme.html)
 - [AWS SAM](https://aws.amazon.com/serverless/sam/)
 - [Service Frameworks](https://www.serverless.com/)
 - [CDK8s](https://github.com/awslabs/cdk8s)

Additionally, check out [RFC 049 of CDK](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0049-continuous-delivery.md). CDK is where a lot of us are banking the future of AWS deployments are.

I don't recall any of these alternatives existing when we started Mu. The increased competition, new ideas, and updates to the ecosystem have made the decision easier to discontinue support for Mu.
