### ISSUE TITLE
Service Log Aggregation

### ISSUE THREAD

**Issue by cplee** [stelligent/mu#77]
Aggregate container logs to CloudWatch logs.  Create log group for each service and log stream for each container

**Comment by cplee** [comment]
@LevonBecker interested??

**Comment by LevonBecker** [comment]
@cplee yeah, the only thing that complicayes it is I do this with a Chef Cookbook that sets up a raw Amazon Linux AMI to be an ECS cluster instance. Which is probably a issue we should create first. This is important because a lot of companies have hardened AMI releases and will mot allow using the pre-baked ECS AMI. I have all the code that would need ro go in the CFN template. Using Chef Zero, CFN writes Chef environment with stack values so cookbook can do it's magic.

**Comment by LevonBecker** [comment]
Once set to use cookbook we can do anything... or we can go ahead and bash it out in CFN template
